# Generated by Django 5.1.1 on 2024-09-25 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0004_rename_date_joined_user_created_at_user_updated_at'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
