# Generated by Django 5.1.1 on 2024-09-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0005_alter_task_user_id_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('complete', 'complete'), ('overdue', 'overdue')], default='pending', max_length=20),
        ),
    ]
