# Generated by Django 5.1.1 on 2024-09-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0006_task_time_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DurationField(null=True),
        ),
    ]
